# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    mkdir -p $(Agent.ToolsDirectory)/_jf/current/
    cd $(Agent.ToolsDirectory)/_jf/current/
    wget -O jf https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/2.56.0/jfrog-cli-linux-amd64/jf
    chmod +x jf
    ln -s $(Agent.ToolsDirectory)/_jf/current/jf /usr/local/bin/jf
    jf -version
  displayName: 'Install JFrog CLI'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    

- script: |
    cd $(Build.Repository.Name)
    jf rt mvn clean install --build-name=$(Build.DefinitionName) --build-number=$(Build.BuildNumber) \
    --repo-resolve="libs-release" --repo-resolve="libs-snapshot" \
    --repo-deploy="libs-release" --repo-deploy="libs-snapshot" \
    --include-env-vars=true
  displayName: 'JFrog Maven Integration'
