trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

parameters:
  - name: ACCESS_TOKEN
    type: string
    default: $(API_KEY)

resources:
  repositories:
    - repository: templates
      type: github
      name: CharinduThisara/azure-pipeline-templates
      endpoint: github.com_CharinduThisara

steps:
- template: ci-pipelines/templates/sca-scan-jfrog.yaml@templates
  parameters:
    ACCESS_TOKEN: ${{ parameters.ACCESS_TOKEN }}
    PROJECT_TYPE: mvn
    GITHUB_ENDPOINT: 'github.com_CharinduThisara'