trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

parameters:
  - name: ACCESS_TOKEN
    type: string
    default: $(API_KEY)

resources:
  repositories:
    - repository: templates
      type: github
      ref: refs/tags/v2.1
      name: CharinduThisara/Charindut-testing
      endpoint: github.com_CharinduThisara

steps:
- template: sca-test-jfrog.yml@templates
  parameters:
    ACCESS_TOKEN: ${{ parameters.ACCESS_TOKEN }}
    PROJECT_TYPE: mvn
    GITHUB_CONNECTION: 'github.com_CharinduThisara'